spring:
  dubbo:
    application:
      name: gmall-user-consumer
    registry:
      address: zookeeper://47.98.210.230:2181
    protocol:
       name: dubbo
       port: 20881
    scan: com.gupao.gpmall.controller

server:
  port: 8090

